version: 2.1
jobs:
  compile:
   docker:
      - image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           git clone https://github.com/farhan-venn/android_kernel_xiaomi_surya/ -b master kernel
           cd kernel
           git clone https://github.com/farhan-venn/myscripts.git -b main
           chmod +x myscripts/clang-setup.sh
           chmod +x myscripts/surya.sh
           source ./myscripts/clang-setup.sh
           ./myscripts/surya.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
