version: 2.1
jobs:
  compile:
   docker:
      - image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           git clone https://github.com/farhan-venn/android_kernel_xiaomi_surya -b master
           git clone https://github.com/kdrag0n/proton-clang -b master /workspace/clang
           chmod +x android_kernel_xiaomi_surya/surya.sh
           ./android_kernel_xiaomi_surya/surya.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
