version: 2.1
jobs:
  compile:
   docker:
      - image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
   steps:
      - run: |
        source build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
