version: 2.1
jobs:
  compile:
   docker:
      - image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           git clone github.com/farhan-venn/android_kernel_xiaomi_surya/ -b master
           chmod +x android_kernel_xiaomi_surya/build.sh
           ./android_kernel_xiaomi_surya/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
